export const GET_INITIAL_ITEMS_SUCCESS= "GET_INITIAL_ITEMS_SUCCESS";
export const GET_INITIAL_ITEMS_FAIL= "GET_INITIAL_ITEMS_FAIL";


export const GET_MORE_ITEMS_SUCCESS = "GET_MORE_ITEMS_SUCCESS";
export const GET_MORE_ITEMS_FAIL = "GET_MORE_ITEMS_FAIL";


export const GET_ONE_ITEM_SUCCESS = "GET_ONE_ITEM_SUCCESS";
export const GET_ONE_ITEM_FAIL = "GET_ONE_ITEM_FAIL";

